title: Julien Corioland
description: 'Software Engineer @ Microsoft - Cloud Native, Containers and DevOps'
url: "http://blog.jcorioland.io"
show_downloads: false
permalink: /archives/:year/:month/:day/:title.html
twitter:
  username: jcorioland
logo: /assets/images/profile.jpg
image: /assets/images/profile.jpg
social:
  name: Julien Corioland
  links:
    - https://twitter.com/jcorioland
    - https://www.linkedin.com/in/juliencorioland
    - https://github.com/jcorioland

excerpt_separator: <!--more-->

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman 
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

version: 1.0
paginate: 5
  