title: Julien Corioland
description: 'Technical blog about Cloud, Containers and DevOps'
url: "http://blog.jcorioland.io"
show_downloads: false
permalink: /archives/:year/:month/:day/:title.html

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman 
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

version: 1.0
paginate: 5
  